-- DDL
create table subscriptions
(
    id                  bigint generated by default as identity
        primary key,
    web_service_name    varchar(255)
        unique,
    web_service_url     varchar(255),
    web_service_user_id varchar(255)
);

alter table subscriptions
    owner to root;

create table users
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255),
    lastname varchar(255),
    name     varchar(255),
    username varchar(255)
        unique
);

alter table users
    owner to root;

create table users_subscriptions
(
    fk_subscription bigint not null
        constraint fk2kwu2xhhlmxf3tauke3gjgu9b
            references subscriptions,
    fk_user         bigint not null
        constraint fkft5jccmulhip2nen4lm3crh02
            references users,
    primary key (fk_subscription, fk_user)
);

alter table users_subscriptions
    owner to root;


-- Initial records
INSERT INTO public.subscriptions (id, web_service_name, web_service_url, web_service_user_id) VALUES (nextval('subscriptions_id_seq'), 'webService01', 'http://webService01.com', 'webService01User01');
INSERT INTO public.subscriptions (id, web_service_name, web_service_url, web_service_user_id) VALUES (nextval('subscriptions_id_seq'), 'webService02', 'http://webService02.com', 'webService02User02');
INSERT INTO public.subscriptions (id, web_service_name, web_service_url, web_service_user_id) VALUES (nextval('subscriptions_id_seq'), 'webService03', 'http://webService03.com', 'webService03User03');
INSERT INTO public.subscriptions (id, web_service_name, web_service_url, web_service_user_id) VALUES (nextval('subscriptions_id_seq'), 'webService04', 'http://webService04.com', 'webService04User04');

INSERT INTO public.users (id, email, lastname, name, username) VALUES (nextval('users_id_seq'), 'email01', 'lastname01', 'name01', 'username01');
INSERT INTO public.users (id, email, lastname, name, username) VALUES (nextval('users_id_seq'), 'email02', 'lastname02', 'name02', 'username02');
INSERT INTO public.users (id, email, lastname, name, username) VALUES (nextval('users_id_seq'), 'email03', 'lastname03', 'name03', 'username03');

INSERT INTO public.users_subscriptions (fk_subscription, fk_user) VALUES (1, 1);
INSERT INTO public.users_subscriptions (fk_subscription, fk_user) VALUES (2, 1);
INSERT INTO public.users_subscriptions (fk_subscription, fk_user) VALUES (4, 1);
INSERT INTO public.users_subscriptions (fk_subscription, fk_user) VALUES (3, 2);
INSERT INTO public.users_subscriptions (fk_subscription, fk_user) VALUES (4, 2);
INSERT INTO public.users_subscriptions (fk_subscription, fk_user) VALUES (1, 3);
INSERT INTO public.users_subscriptions (fk_subscription, fk_user) VALUES (4, 3);
